In [84]:
import cv2
import time
import PIL as Image
import pytesseract
import pandas as pd
import numpy as np
import re

In [85]:
image_file = "invoices/batch1-0371.jpg"

In [86]:
# read the image
img = cv2.imread(image_file)

In [87]:
# resize the image
img = cv2.resize(img , (420,800))

In [88]:
# shows the image and destory the window to stop the kernal from crashing 


cv2.imshow("Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [89]:
###### Below code is to save the text of invoice into csv file (not field wise)" ######

In [90]:
# setting the teresset path
pytesseract.pytesseract.tesseract_cmd=r'C:/Program Files/Tesseract-OCR/tesseract.exe'

In [91]:
text = pytesseract.image_to_string(image_file)

In [92]:
text

'Invoice no: 39652805\n\nDate of issue: 03/20/2020\n\nSeller: Client:\n\nLewis and Sons Hancock LLC\n\n256 Cruz Views Suite 230 04712 Andrew Meadows\nEast Justin, WA 50904 North Hannah, NV 36457\nTax Id: 988-97-7797 Tax Id: 982-72-2795\n\nIBAN: GB51EXRQ57779404817003\n\nITEMS\nNo. Description Qty UM Net price Net worth VAT [%] Gross\nworth\ntks computer 1,00 each 299,99 299,99 10% 329,99\nSUMMARY\nVAT [%] Net worth VAT Gross worth\n10% 299,99 30,00 329,99\n\nTotal $ 299,99 $ 30,00 $ 329,99\n'

In [93]:
df = pd.DataFrame({
    "image_name": ["batch1-0371.jpg"],
    "extracted_text": [text]
})

In [94]:
df

        image_name                                     extracted_text
0  batch1-0371.jpg  Invoice no: 39652805\n\nDate of issue: 03/20/2...

In [95]:
###### Below code is to save the text of invoice in a structured way of sr number and coloumn of text_line into csv file (not field wise)" ######

In [96]:
df.to_csv("invoice_text.csv", index=False)

In [97]:
lines = text.split("\n")

In [98]:
lines

['Invoice no: 39652805',
 '',
 'Date of issue: 03/20/2020',
 '',
 'Seller: Client:',
 '',
 'Lewis and Sons Hancock LLC',
 '',
 '256 Cruz Views Suite 230 04712 Andrew Meadows',
 'East Justin, WA 50904 North Hannah, NV 36457',
 'Tax Id: 988-97-7797 Tax Id: 982-72-2795',
 '',
 'IBAN: GB51EXRQ57779404817003',
 '',
 'ITEMS',
 'No. Description Qty UM Net price Net worth VAT [%] Gross',
 'worth',
 'tks computer 1,00 each 299,99 299,99 10% 329,99',
 'SUMMARY',
 'VAT [%] Net worth VAT Gross worth',
 '10% 299,99 30,00 329,99',
 '',
 'Total $ 299,99 $ 30,00 $ 329,99',
 '']

In [99]:
df = pd.DataFrame(lines, columns=["text_line"])
df

                                            text_line
0                                Invoice no: 39652805
1
2                           Date of issue: 03/20/2020
3
4                                     Seller: Client:
5
6                          Lewis and Sons Hancock LLC
7
8       256 Cruz Views Suite 230 04712 Andrew Meadows
9        East Justin, WA 50904 North Hannah, NV 36457
10            Tax Id: 988-97-7797 Tax Id: 982-72-2795
11
12                       IBAN: GB51EXRQ57779404817003
13
14                                              ITEMS
15  No. Description Qty UM Net price Net worth VAT...
16                                              worth
17    tks computer 1,00 each 299,99 299,99 10% 329,99
18                                            SUMMARY
19                  VAT [%] Net worth VAT Gross worth
20                            10% 299,99 30,00 329,99
21
22                    Total $ 299,99 $ 30,00 $ 329,99
23

In [100]:
df.to_csv("invoice_text_lines_stryctured.csv", index=False)

In [107]:
###### main Stuctured code to save image into csv with respective fields" ######

In [108]:


invoice_no = re.search(r"Invoice no:\s*(\d+)", text)
date = re.search(r"Date of issue:\s*([0-9/]+)", text)
total = re.search(r"Total \$\s*([0-9.,]+)", text)


data = {
    "invoice_no": invoice_no.group(1) if invoice_no else "",
    "date": date.group(1) if date else "",
    "total_amount": total.group(1) if total else ""
}

df = pd.DataFrame([data])
df.to_csv("tabular-field.csv", index=False)

In [109]:
invoice_no,date,total

(<re.Match object; span=(0, 20), match='Invoice no: 39652805'>,
 <re.Match object; span=(22, 47), match='Date of issue: 03/20/2020'>,
 <re.Match object; span=(440, 454), match='Total $ 299,99'>)